Added build error output for cross compile

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -240,7 +240,19 @@ jobs:
             -DSTRINGZILLA_BUILD_BENCHMARK=1 \
             -DSTRINGZILLA_BUILD_TEST=1
 
-          cmake --build build_artifacts --config RelWithDebInfo
+          cmake --build build_artifacts --config RelWithDebInfo > build_artifacts/logs.txt 2>&1 || {
+            echo "Compilation failed. Here are the logs:"
+            cat build_artifacts/logs.txt
+            echo "The original compilation commands:"
+            cat build_artifacts/compile_commands.json
+            echo "CPU Features:"
+            lscpu
+            echo "Clang Version:"
+            clang --version
+            echo "Clang++ Version:"
+            clang++ --version
+            exit 1
+          }
 
         # We can't run the produced builds, but we can make sure they exist
       - name: Test artifacts presense
